spring.application.name=ms-pedidos360-bff

server.port=${PORT:8080}

orders.service.url=${ORDERS_SERVICE_URL:http://localhost:8081}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8082}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/7d9b0753-76e0-4904-bc68-abb1c917b695/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=6faf8448-cd68-430c-a4f6-4ac7726e5faa