spring.application.name=ms-pedidos360-catalog

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=local
server.port=8082