spring.application.name=pedidos360

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update