spring.application.name=ms-pedidos360-orders
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360_orders
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=local
server.port=8081
catalog.service.url=http://localhost:8082
